[package]
name = "liq-routing"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
liq-core = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
